services:
  db:
    image: postgres:18-alpine
    command: -c config_file=/etc/postgresql_config/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=backend_database
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./postgresql_config:/etc/postgresql_config
