services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: transcendence_frontend
    volumes:
      - ./frontend:/app
    # ports:
    #   - 8080:5173
    networks:
      - trans_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: transcendence_backend
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trans_network
    environment:
      # Backend API needs to know its own directory (for file saving)
      - BACKEND_ROOT_PATH=/app
      
      # Backend auto-defaults this to 3000 anyways
      # - BACKEND_PORT=${BACKEND_PORT}

      # Login details to connect to the database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}

      # This is the URL backend returns for static files
      - BACKEND_URL=http://localhost:${NGINX_PORT}
  
  db:
    image: postgres:18-alpine
    container_name: transcendence_db
    command: -c config_file=/etc/postgresql_config/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      #! This port is open for development purposes only so you can what is in the database
      #! For developing Frontend, use PORT 8080 only
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql_config:/etc/postgresql_config
    networks:
      - trans_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: transcendence_nginx
    ports:
      - "${NGINX_PORT:-8080}:8080"
    depends_on:
      - backend
      - frontend
    networks:
      - trans_network
    restart: unless-stopped

networks:
  trans_network:
    driver: bridge

volumes:
  postgres_data:
